# Tensors 
## <span style='color:yellow'>In this tutorial, we will explore how to manipulate tensors and perform basic operations.</span>

# Pytorch and Numpy Conversion 
## <span style='color:yellow'>PyTorch primarily relies on tensor operations.</span>
## <span style='color:yellow'>In numpy, data is represented as vectors and arrays.</span>
## <span style='color:yellow'> PyTorch represents data as tensors that can exist in different dimensions, such as 1-D, 2-D, 3-D, and so forth.</span>

# Creating tensors 


In [2]:
# Creating an empty tensor with a scalar value
import torch
x=torch.empty(1)
print(x)

# Cretaing 1-d vector with three elements
x=torch.empty(3)
print(x)

# Cretaing an array of 2 rows and 3 columns
x=torch.empty(2,3)
print(x)

# Cretaing 3-d tensor
x=torch.empty(2,2,3)
print(x)

tensor([0.])
tensor([-7.9798e-24,  3.0775e-41,  2.2801e-13])
tensor([[-9.8499e-27,  3.0775e-41, -8.0315e-24],
        [ 3.0775e-41,  8.9683e-44,  0.0000e+00]])
tensor([[[0.0000e+00, 0.0000e+00, 2.3824e-14],
         [4.5712e-41, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [3]:
# Creating a tensor with random float values
x=torch.rand(3,3)
print(x)

tensor([[0.9806, 0.8670, 0.6571],
        [0.2288, 0.4661, 0.8821],
        [0.2974, 0.4568, 0.5876]])


In [4]:
# Creating a zero tensor
x=torch.zeros(3,3)
print(x)
print("")
# Creating a tensor of ones
x=torch.ones(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [67]:
# The default data type is float32, but we can change that to any data type.
print(x.dtype)
print(" ")

# Create a tensor with int values
x=torch.ones(3,3,dtype=torch.int)
print(x)
print(" ")
# Create a tensor with float16 values
x=torch.ones(3,3,dtype=torch.float16)
print(x)
print(x.size())


torch.float32
 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.Size([3, 3])


In [5]:
# Construct a tensor form data, e.g., a list
x=torch.tensor([2.5,2.3])
print(x)

tensor([2.5000, 2.3000])


# Basic operations


In [7]:
x=torch.rand(3,3)
y=torch.rand(3,3)

print(x); print(""), print(y) 

tensor([[0.5766, 0.2793, 0.9393],
        [0.6883, 0.8253, 0.7010],
        [0.1870, 0.7968, 0.1098]])

tensor([[0.6917, 0.6036, 0.5631],
        [0.5804, 0.1175, 0.4490],
        [0.2280, 0.7360, 0.0334]])


(None, None)

In [8]:
# Addition
z=x+y
print(z)
print(" ")

# Alternative addition
z=torch.add(x,y)
print(z)
print("")

# Inplace addition
y.add_(x)  # Note in the Pytorch any method that contains trailing _ is applied in place.
print(y)  

tensor([[1.2682, 0.8829, 1.5025],
        [1.2687, 0.9427, 1.1500],
        [0.4149, 1.5328, 0.1432]])
 
tensor([[1.2682, 0.8829, 1.5025],
        [1.2687, 0.9427, 1.1500],
        [0.4149, 1.5328, 0.1432]])

tensor([[1.2682, 0.8829, 1.5025],
        [1.2687, 0.9427, 1.1500],
        [0.4149, 1.5328, 0.1432]])


In [9]:
# Subtraction
z=x-y
print(z)

tensor([[-0.6917, -0.6036, -0.5631],
        [-0.5804, -0.1175, -0.4490],
        [-0.2280, -0.7360, -0.0334]])


In [10]:
# Multiplication
z= x*y
print(z)
print("")

z=torch.mul(x,y)
print(z)

tensor([[0.7312, 0.2466, 1.4113],
        [0.8732, 0.7780, 0.8061],
        [0.0776, 1.2214, 0.0157]])

tensor([[0.7312, 0.2466, 1.4113],
        [0.8732, 0.7780, 0.8061],
        [0.0776, 1.2214, 0.0157]])


In [15]:
# Slicing operation
x=torch.rand(5,3)
print(x)
print(" ")
print(x[:])
print("")

# Printing the first column of data
print(x[:,0])
print("")

# Printing the first row of data
print(x[0,:])
print('')
# Unpacking the value of a tensor of one item of one tensor
print(x[1,2].item())
# The above method is used with a tensor of one item only to be converted into python scalar

tensor([[0.2813, 0.6537, 0.5260],
        [0.5614, 0.7041, 0.6153],
        [0.3806, 0.2670, 0.5228],
        [0.4200, 0.4503, 0.7490],
        [0.2669, 0.4182, 0.9161]])
 
tensor([[0.2813, 0.6537, 0.5260],
        [0.5614, 0.7041, 0.6153],
        [0.3806, 0.2670, 0.5228],
        [0.4200, 0.4503, 0.7490],
        [0.2669, 0.4182, 0.9161]])

tensor([0.2813, 0.5614, 0.3806, 0.4200, 0.2669])

tensor([0.2813, 0.6537, 0.5260])

0.6153056025505066


In [11]:
# Reshaping tensor
x=torch.rand(4,4)
print(x)
print(" ")
y=x.view(16)
print(y)
print(" ")

x=torch.rand(18)
y=x.view(9,2)
print(y)

tensor([[0.9241, 0.3915, 0.3164, 0.2593],
        [0.1752, 0.4162, 0.0398, 0.7481],
        [0.9380, 0.2594, 0.7280, 0.0851],
        [0.6097, 0.9400, 0.7184, 0.8456]])
 
tensor([0.9241, 0.3915, 0.3164, 0.2593, 0.1752, 0.4162, 0.0398, 0.7481, 0.9380,
        0.2594, 0.7280, 0.0851, 0.6097, 0.9400, 0.7184, 0.8456])
 
tensor([[0.7392, 0.8282],
        [0.7864, 0.1779],
        [0.3874, 0.4246],
        [0.5933, 0.3213],
        [0.7418, 0.4424],
        [0.8600, 0.4696],
        [0.4687, 0.4312],
        [0.0561, 0.2449],
        [0.5461, 0.3221]])


In [20]:
# If you do not want to specify the first shape arguments (# rows), then pass -1 and Pytorch will automaticaaly select the best shape
x=torch.rand(18)
y=x.view(-1,9)
print(y)

tensor([[0.7152, 0.4581, 0.2520, 0.7003, 0.2104, 0.8307, 0.9998, 0.4327, 0.7307],
        [0.6956, 0.2398, 0.3148, 0.8643, 0.9919, 0.2183, 0.1639, 0.0801, 0.6860]])


# Numpy and Pytorch conversion


In [13]:
import numpy as np

# Creating a tensor of ones
x=torch.ones(5)
print(x)
print(" ")
# Conversion to numpy
y=x.numpy()
print(y)
print(type(y))

tensor([1., 1., 1., 1., 1.])
 
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [15]:
# Note: If the tensors are located in the CPU (NOT the GPUs), then the tensor and converted np array point to the same memory address.
x=torch.ones(5)
print(x)
print(" ")

# Conversion to numpy
y=x.numpy()
print(y)
print(" ")

# Let us add 3 inplace to all matrix x. Note again: anay  method with trainling _ is used in place
x.add_(3)
print(x)
print(y)

# Thus be carfull when you make the conversion and using the inplace methods


tensor([1., 1., 1., 1., 1.])
 
[1. 1. 1. 1. 1.]
 
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [21]:
# Numpy to Pytorch conversion
x=np.ones(5)
print(x)

# Coversion
y = torch.from_numpy(x)
y1 = torch.from_numpy(x).to(torch.float32)

print(y)
print(" ")

x+=5

print(x)
print(" ")
print(y)
print(" ")
print(y1)  # This will not be modified

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
 
[6. 6. 6. 6. 6.]
 
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
 
tensor([1., 1., 1., 1., 1.])


In [22]:
# Check if the GPU is available or not
if torch.cuda.is_available():
    print(f'The total number of availabe GPUs are: {torch.cuda.device_count()}')

for i in range(torch.cuda.device_count()):
    device=torch.cuda.get_device_properties(i)
    print(f'\nDetails from the GPU {i}')
    print(f'Name : {device.name}')
    print(f'Compute cabability: {device.major}.{device.minor}')
    print(f'Total memory: {device.total_memory/1024**3:.2f} GB')


The total number of availabe GPUs are: 4

Details from the GPU 0
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB

Details from the GPU 1
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB

Details from the GPU 2
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB

Details from the GPU 3
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB


In [23]:
# Creating a tensor into a GPU
if torch.cuda.is_available():
    device=torch.device("cuda:0") # We can set the desired gpu
    x=torch.rand(5,5,device=device)
    # Alternativelly
    y=torch.rand(5,5)
    y=y.to(device)
    # Addition
    z=x+y
    print(z)

tensor([[1.0930, 1.5082, 0.3159, 0.6554, 0.5713],
        [1.6058, 0.7760, 0.7064, 0.7070, 0.4914],
        [1.1805, 0.6797, 0.9797, 1.1089, 1.7404],
        [1.4968, 0.9599, 1.3378, 1.2644, 1.1787],
        [1.3601, 0.7138, 0.4702, 1.6812, 0.6898]], device='cuda:0')


In [24]:
# Note: Numpy can handle only cpu tensors, thus the follwoing line of code will return an error
#z.numpy()

# Thus we can move z from the GPU to cpu to convert it into numpy
z=z.to("cpu")

znumpy=z.numpy()
print(type(znumpy))

<class 'numpy.ndarray'>


In [37]:
# Telling pytorch that the tensor need to calculate the gradient
x=torch.rand(5,6,requires_grad=True) 
print(x) # requires_grad=True will be printed and in informs teh pytorch that the tensor require gradient calculations.

tensor([[0.1184, 0.4573, 0.5545, 0.1520, 0.5867, 0.6577],
        [0.2050, 0.3934, 0.4485, 0.9007, 0.0036, 0.3371],
        [0.0056, 0.5949, 0.8334, 0.0306, 0.7424, 0.8395],
        [0.4566, 0.2756, 0.9948, 0.7113, 0.0781, 0.5844],
        [0.1381, 0.2350, 0.8446, 0.5974, 0.3487, 0.8691]], requires_grad=True)


In [27]:
x=torch.rand(5,5,requires_grad=True)
print(x)

tensor([[0.8278, 0.0268, 0.8620, 0.0368, 0.6558],
        [0.3227, 0.1824, 0.3449, 0.4699, 0.8693],
        [0.3718, 0.6464, 0.3250, 0.1720, 0.6946],
        [0.7781, 0.3550, 0.7605, 0.2204, 0.9655],
        [0.6405, 0.1738, 0.8970, 0.4033, 0.4720]], requires_grad=True)
