# Tensors 
## <span style='color:yellow'>In this tutorial, we will explore how to manipulate tensors and perform basic operations.</span>

# Pytorch and Numpy Conversion 
## <span style='color:yellow'>PyTorch primarily relies on tensor operations.</span>
## <span style='color:yellow'>In numpy, data is represented as vectors and arrays.</span>
## <span style='color:yellow'> PyTorch represents data as tensors that can exist in different dimensions, such as 1-D, 2-D, 3-D, and so forth.</span>

# Creating tensors 


In [67]:
# Creating an empty tensor with a scalar value, actuly it contains random values 
import torch
x=torch.empty(1)
print(x)

# Cretaing 1-d vector with three elements
x=torch.empty(3)
print(x)

# Cretaing an array of 2 rows and 3 columns
x=torch.empty(2,3)
print(x)

# Cretaing an array of 2 rows and 3 columns with size keyword
x=torch.empty(size=(2,3))
print(x)

# Cretaing 3-d tensor
x=torch.empty(2,2,3)
print(x)

tensor([1.6590e-24])
tensor([0.0000e+00, 6.7262e-44, 1.0563e-05])
tensor([[1.4727e-34, 0.0000e+00, 1.6598e-37],
        [0.0000e+00, 8.9683e-44, 0.0000e+00]])
tensor([[1.4610e-34, 0.0000e+00, 1.6649e-37],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])
tensor([[[1.4903e-34, 0.0000e+00, 1.6590e-24],
         [4.5758e-41, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [68]:
# Creating a tensor with random float values
x=torch.rand(3,3)
print(x)

tensor([[0.5900, 0.3172, 0.0128],
        [0.6074, 0.6437, 0.7279],
        [0.8216, 0.2308, 0.4287]])


In [69]:
# Creating a zero tensor
x=torch.zeros(3,3)
print(x)
print("")
# Creating a tensor of ones
x=torch.ones(3,3)
print(x)
print("")

# Creating a tensor of identity matrix, I=eye
x=torch.eye(3,3)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [70]:
# Creating a tensor for a range of values
x=torch.arange(start=0,end=5,step=1)  # 5 is execluded
print(x)
print("")

# Creating a tensor with a range of linearly-spaced values
x=torch.linspace(start=0.1,end=1,steps=10)  # 1 is included
print(x)


tensor([0, 1, 2, 3, 4])

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [41]:
# Creating and empty tensor and then filling it with random values
x=torch.empty(size=(3,3)).normal_(mean=0,std=1)
print(x)

# Creating and empty tensor and then filling it with uniform distribution with a range of 0 to 1
x=torch.empty(size=(3,3)).uniform_(0,1)
print(x)

# Craeting a tensor with ones in the diagonal and zeros elsewhere (same as torch.eye)
x=torch.diag(torch.ones(5))
print(x)

# Creating a tensor with repeated values
x=torch.full((6,),5)
print(x)

# Creating a diagonla matrix with values of 5 at the diagonal
x=torch.diag(torch.full((5,),5))
print(x)

# Creating a 2-D matrix and fill it with
x=torch.full((3,3),5)
print(x)

tensor([[ 2.9420,  0.3974,  0.1368],
        [ 0.9126, -0.5145, -0.1995],
        [ 1.0370,  0.0701,  0.4484]])
tensor([[0.9256, 0.5714, 1.0000],
        [0.6685, 0.0617, 0.9041],
        [0.0899, 0.8458, 0.1956]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([5, 5, 5, 5, 5, 5])
tensor([[5, 0, 0, 0, 0],
        [0, 5, 0, 0, 0],
        [0, 0, 5, 0, 0],
        [0, 0, 0, 5, 0],
        [0, 0, 0, 0, 5]])
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [67]:
# The default data type is float32, but we can change that to any data type.
print(x.dtype)
print(" ")

# Create a tensor with int values
x=torch.ones(3,3,dtype=torch.int)
print(x)
print(" ")
# Create a tensor with float16 values
x=torch.ones(3,3,dtype=torch.float16)
print(x)
print(x.size())


torch.float32
 
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)
torch.Size([3, 3])


In [47]:
# Converting a tensor to boolean tensor
x=torch.arange(0,5)
print(x.bool())
print(x.short())  # int16  Not used too much
print(x.long())   # int64  Not used too much
print(x.half())   # float16 if you want to train with less precision
print(x.float())  # float32
print(x.double()) # float64

tensor([False,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4], dtype=torch.int16)
tensor([0, 1, 2, 3, 4])
tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4.])
tensor([0., 1., 2., 3., 4.], dtype=torch.float64)


In [6]:
# Construct a tensor form data, e.g., a list
x=torch.tensor([2.5,2.3])
print(x)

# Construct a tensor form data, with two rowa and three columns
x=torch.tensor([[2.5,2.3],[3.5,3.3]])
print(x)

tensor([2.5000, 2.3000])
tensor([[2.5000, 2.3000],
        [3.5000, 3.3000]])


In [71]:
# Construct a tensor form uniform distribution
x=torch.rand(3,3)
print(x)

tensor([[0.1548, 0.0867, 0.3322],
        [0.7407, 0.8050, 0.4341],
        [0.6616, 0.0183, 0.0089]])


# Basic operations


In [50]:
x=torch.rand(3,3)
y=torch.rand(3,3)

print(x); print(""), print(y) 

tensor([[0.8425, 0.6785, 0.7375],
        [0.1565, 0.1295, 0.9566],
        [0.4427, 0.7676, 0.4728]])

tensor([[0.7086, 0.4885, 0.7117],
        [0.1611, 0.0394, 0.5918],
        [0.8605, 0.5656, 0.8052]])


(None, None)

In [8]:
# Addition
z=x+y
print(z)
print(" ")

# Alternative addition
z=torch.add(x,y)
print(z)
print("")

# Inplace addition
y.add_(x)  # Note in the Pytorch any method that contains trailing _ is applied in place.
print(y)  

tensor([[1.2682, 0.8829, 1.5025],
        [1.2687, 0.9427, 1.1500],
        [0.4149, 1.5328, 0.1432]])
 
tensor([[1.2682, 0.8829, 1.5025],
        [1.2687, 0.9427, 1.1500],
        [0.4149, 1.5328, 0.1432]])

tensor([[1.2682, 0.8829, 1.5025],
        [1.2687, 0.9427, 1.1500],
        [0.4149, 1.5328, 0.1432]])


In [9]:
# Subtraction
z=x-y
print(z)

tensor([[-0.6917, -0.6036, -0.5631],
        [-0.5804, -0.1175, -0.4490],
        [-0.2280, -0.7360, -0.0334]])


In [51]:
# division
z=x/y
print(z)
print("")

# Alternative division
z=torch.true_divide(x,y)
print(z)

tensor([[1.1890, 1.3890, 1.0362],
        [0.9716, 3.2850, 1.6164],
        [0.5144, 1.3572, 0.5872]])

tensor([[1.1890, 1.3890, 1.0362],
        [0.9716, 3.2850, 1.6164],
        [0.5144, 1.3572, 0.5872]])


In [59]:
# Multiplication (element wise multiplication)
z= x*y
print(z)
print("")

z=torch.mul(x,y)
print(z)

tensor([[0.5970, 0.3315, 0.5249],
        [0.0252, 0.0051, 0.5662],
        [0.3809, 0.4342, 0.3807]])

tensor([[0.5970, 0.3315, 0.5249],
        [0.0252, 0.0051, 0.5662],
        [0.3809, 0.4342, 0.3807]])
tensor([[1.3409, 0.8554, 1.5950],
        [0.9550, 0.6226, 0.9583],
        [0.8442, 0.5139, 1.1501]])


In [66]:
# Matrix multiplication

'''
Dot Product: The dot product of two vectors b (often represented as 
a⋅b) is a scalar (a single number) obtained by multiplying the corresponding entries of the two vectors and then summing those products.
Matrix Multiplication: Matrix multiplication involves taking the dot products of rows of the first matrix with the columns of the second matrix. 

In general, matrix multiplication can be seen as an extension of the dot product concept,
transitioning from operations between vectors to operations between matrices
'''
z=torch.mm(x,y)  
print(z)
print("")

z=x.mm(y)  
print(z)
print("")

z=x@y
print(z)
print("")


tensor([[1.3409, 0.8554, 1.5950],
        [0.9550, 0.6226, 0.9583],
        [0.8442, 0.5139, 1.1501]])

tensor([[1.3409, 0.8554, 1.5950],
        [0.9550, 0.6226, 0.9583],
        [0.8442, 0.5139, 1.1501]])

tensor([[1.3409, 0.8554, 1.5950],
        [0.9550, 0.6226, 0.9583],
        [0.8442, 0.5139, 1.1501]])



In [54]:
# Exponentiation
# Elemnt wise exponentiation
z=x.pow(2)
print(z)
print("")
# Alternative
z=x**2
print(z)


tensor([[0.7098, 0.4604, 0.5439],
        [0.0245, 0.0168, 0.9152],
        [0.1960, 0.5892, 0.2236]])

tensor([[0.7098, 0.4604, 0.5439],
        [0.0245, 0.0168, 0.9152],
        [0.1960, 0.5892, 0.2236]])


In [68]:
# Matrix exponentiation (e.g., e^x) not element wise
z=x.matrix_power(6) # like consider multiplying x by itself 6 times
print(z)

tensor([[ 9.0744, 10.6624, 13.7826],
        [ 4.6985,  5.5344,  7.1115],
        [ 6.2134,  7.2940,  9.4534]])


In [70]:
# Dot product: Element-wise multiplication between two vectors, then sum all the elements 
x_=torch.rand(5)
y_=torch.rand(5)
z_=torch.dot(x_,y_)
print(z_) # It is a scalar, i.e., the sum of teh product of the elements of x_ and y_


tensor(0.8994)


In [78]:
# Batch matrix multiplication: will have three dimensions and the first dimension will be the batch size

batch=32
m=10
n=20
x_=torch.rand(batch,m,n)
print(x_.shape)
print("")

y_=torch.rand(batch,m,n)
print(y_.shape)
print("")

z_=torch.bmm(x_,y_.transpose(1,2)) # transpose(1,2) means transpose the second and third dimensions
print(z_.shape)


# Anothe example of batch matrix multiplication
m=10
n=20
p=30
x_=torch.rand(batch,m,n)
print(x_.shape)
print("")

y_=torch.rand(batch,n,p)
print(y_.shape)
print("")

z_=torch.bmm(x_,y_)
print(z_.shape)  # The result shape is (batch,m,p)

torch.Size([32, 10, 20])

torch.Size([32, 10, 20])

torch.Size([32, 10, 10])
torch.Size([32, 10, 20])

torch.Size([32, 20, 30])

torch.Size([32, 10, 30])


In [86]:
# Broadcasting: It is a way of making the tensor of different shapes compatible for element wise operations
x_=torch.rand((7,7))
y_=torch.rand((1,7))

z=x_-y_
print(z)
print("")

x_ = torch.ones(5, 3)
y_ = torch.tensor([1, 2, 3])
z_ = x_ - y_  # y_ is broadcasted to match the shape of B.
print(z_)
print("")

z_=x_**y_
print(z_)


tensor([[-0.7563, -0.4522,  0.0286,  0.3471,  0.1631,  0.1275,  0.0258],
        [ 0.1677, -0.0206, -0.0339, -0.3295,  0.1852, -0.2167,  0.0493],
        [-0.1145, -0.1452,  0.1168,  0.0798,  0.0321, -0.1144,  0.2216],
        [ 0.0217, -0.4696, -0.2065,  0.4021, -0.1430, -0.4055,  0.8285],
        [-0.4057, -0.3355,  0.2379, -0.1755, -0.0353, -0.2844,  0.5057],
        [ 0.0780, -0.6872,  0.1508,  0.2999,  0.2472, -0.6879,  0.3021],
        [ 0.2134,  0.2083,  0.4940,  0.0635,  0.7313, -0.3155,  0.3513]])

tensor([[ 0., -1., -2.],
        [ 0., -1., -2.],
        [ 0., -1., -2.],
        [ 0., -1., -2.],
        [ 0., -1., -2.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [72]:
# Simple comparison (element wise comparison)
z=x>0.5 # we can use any comparison operator
print(z)
print("")
# Comparison of two tensors
x=torch.tensor([1,2,3,4,5])
y=torch.tensor([6,7,2,4,5])
print(x.eq(y)) # element wise comparison
print("")
print(torch.eq(x,y)) # element wise comparison

tensor([[False, False, False],
        [ True,  True, False],
        [ True, False, False]])

tensor([False, False, False,  True,  True])

tensor([False, False, False,  True,  True])


In [96]:
# Summing all the elements of a tensor
x=torch.rand(3,3)
sum_x=torch.sum(x,dim=0) # sum along the rows
print(sum_x)
print("")

# Maxiumn value of a tensor
vals,idxs=torch.max(x,dim=0) # Max along the rows
print(vals)
print(idxs)
print("")

# argmax returns the index of the maximum value as torch.max 
idxs=torch.argmax(x,dim=0) 
print(idxs)
print("")

# Minimum value of a tensor
vals,idxs=torch.min(x,dim=0) # Min along the rows
print(vals)
print(idxs)
print("")

# argmin returns the index of the minimum value as as torch.min
idxs=torch.argmin(x,dim=0) 
print(idxs)
print("")

# Absolute value
x=torch.tensor([-1,-2,3,4,-5])
print(torch.abs(x))
print("")

# Mean value of a tensor: Note that the values should be float
x=torch.tensor([1.,2,3,4,5])
z=torch.mean(x.float(),dim=0)
print(z)


tensor([1.7613, 1.2500, 1.6376])

tensor([0.7960, 0.6951, 0.6432])
tensor([0, 1, 0])

tensor([0, 1, 0])

tensor([0.4439, 0.1717, 0.4159])
tensor([2, 0, 2])

tensor([2, 0, 2])

tensor([1, 2, 3, 4, 5])

tensor(3.)


In [15]:
# Slicing and indexing operation
x=torch.rand(5,3)
print(x)
print(" ")
print(x[:])
print("")

# Printing the first column of data
print(x[:,0])
print("")

# Printing the first row of data
print(x[0,:])
print('')
# Unpacking the value of a tensor of one item of one tensor
print(x[1,2].item())
# The above method is used with a tensor of one item only to be converted into python scalar

tensor([[0.2813, 0.6537, 0.5260],
        [0.5614, 0.7041, 0.6153],
        [0.3806, 0.2670, 0.5228],
        [0.4200, 0.4503, 0.7490],
        [0.2669, 0.4182, 0.9161]])
 
tensor([[0.2813, 0.6537, 0.5260],
        [0.5614, 0.7041, 0.6153],
        [0.3806, 0.2670, 0.5228],
        [0.4200, 0.4503, 0.7490],
        [0.2669, 0.4182, 0.9161]])

tensor([0.2813, 0.5614, 0.3806, 0.4200, 0.2669])

tensor([0.2813, 0.6537, 0.5260])

0.6153056025505066


In [18]:
batch_size=15
features=20
x=torch.rand(batch_size,features)
# To show the first sample of the batch
print(x[0]) # = x[0,:]
print("")

# To show the shape of the first sample of the batch
print(x[0].shape)
print("")
# To see the first feature over all samples
print(x[:,0])
print("")
# Feature value update
x[0,0]=9999
print(x[0,:])

tensor([0.8301, 0.9952, 0.6584, 0.9640, 0.6179, 0.6423, 0.7284, 0.2951, 0.8792,
        0.1873, 0.8834, 0.4428, 0.6125, 0.9796, 0.7261, 0.0301, 0.3052, 0.6889,
        0.5245, 0.5986])

torch.Size([20])

tensor([0.8301, 0.2297, 0.2424, 0.1125, 0.8853, 0.4135, 0.9356, 0.3309, 0.8056,
        0.1464, 0.8970, 0.6053, 0.4129, 0.9959, 0.3379])

tensor([9.9990e+03, 9.9521e-01, 6.5839e-01, 9.6399e-01, 6.1795e-01, 6.4226e-01,
        7.2838e-01, 2.9513e-01, 8.7923e-01, 1.8730e-01, 8.8343e-01, 4.4280e-01,
        6.1246e-01, 9.7959e-01, 7.2606e-01, 3.0144e-02, 3.0516e-01, 6.8890e-01,
        5.2452e-01, 5.9855e-01])


In [40]:
# Fancy indexing
x=torch.arange(15)
idxs=[2,4,6,8]
print(x[idxs])
print("")

x=torch.rand(10,10)
rows= torch.tensor([1,2,3])
columns=torch.tensor([1,5,3])
print(x[rows,columns])
print("")

# Advanced Indexing
x=torch.arange(20)
print(x[(x<2) | (x>9)]) # pick values that  < 2 OR > 9
print("")

print(x[(x<2) & (x>9)]) # pick values that  < 2 AND > 9
print(" ")

# Modulos sclicing
print(x[x.remainder(2)==0])



tensor([2, 4, 6, 8])

tensor([0.3885, 0.3524, 0.9628])

tensor([ 0,  1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

tensor([], dtype=torch.int64)
 
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [41]:
#  The 'where' operation is used to verify the value and update the value if a condition is met
x=torch.arange(20)
print(torch.where(x>6,x,x/2)) # if x>6 then x else x/2


tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  7.0000,
         8.0000,  9.0000, 10.0000, 11.0000, 12.0000, 13.0000, 14.0000, 15.0000,
        16.0000, 17.0000, 18.0000, 19.0000])


In [45]:
# Unique operation
x=torch.tensor([0,1,2,3,4,4,5,5,6,0,1,2])
print(x.unique())
print("")

# ndimension
x=torch.rand((5,3,5))
print(x.ndimension())
print("")

# Counting the number of elements in a tensor (useful to check how many weighs parameters in a neural network)
print(x.numel())

tensor([0, 1, 2, 3, 4, 5, 6])

3

75


In [104]:
# Sorting tensor
x=torch.rand(4,4)
print(x)
print("")
sorted_val, idxs=torch.sort(x,dim=0,descending=False) # sort along the rows
print("")
print(sorted_val)

tensor([[0.2080, 0.7496, 0.3791, 0.2435],
        [0.1031, 0.8237, 0.8971, 0.0366],
        [0.5213, 0.7330, 0.5563, 0.6467],
        [0.7369, 0.0575, 0.1787, 0.1076]])


tensor([[0.1031, 0.0575, 0.1787, 0.0366],
        [0.2080, 0.7330, 0.3791, 0.1076],
        [0.5213, 0.7496, 0.5563, 0.2435],
        [0.7369, 0.8237, 0.8971, 0.6467]])


In [110]:
# Checking all elements of a tensor are  less than a value (e.g 0) and fill them to 0 ( if you set min=0.3 then all nums <0.3 will be filled with 0.3) will be filled with 0.3) 
z=torch.clamp(x,min=0)  # The same for max
print(z)
print("")

z=torch.clamp(x,min=0.2)
print(z)
print("")


tensor([[0.2080, 0.7496, 0.3791, 0.2435],
        [0.1031, 0.8237, 0.8971, 0.0366],
        [0.5213, 0.7330, 0.5563, 0.6467],
        [0.7369, 0.0575, 0.1787, 0.1076]])

tensor([[0.2080, 0.7496, 0.3791, 0.2435],
        [0.2000, 0.8237, 0.8971, 0.2000],
        [0.5213, 0.7330, 0.5563, 0.6467],
        [0.7369, 0.2000, 0.2000, 0.2000]])



In [74]:
# any condition if any value is true then it will return true
x=torch.tensor([1,0,1,0,1],dtype=torch.bool)
z=torch.any(x)
print(z)

# all condition if all values are true then it will return true
z= torch.all(x)
print(z)

tensor(True)
tensor(False)


In [47]:
# Reshaping tensor
x=torch.rand(4,4)
print(x)
print(" ")
y=x.view(16)
print(y)
print(" ")

x=torch.rand(18)
y=x.view(9,2)  
print(y)
print(" ")

# reshape is used to reshape a tensor also. The 'view' is used more often and with contiguous memory (adjacent and in sequential order)
x=torch.arange(25)
y=x.reshape(5,5)
print(y)

tensor([[0.1047, 0.5071, 0.0542, 0.3330],
        [0.8789, 0.9451, 0.8701, 0.3063],
        [0.7993, 0.7721, 0.3849, 0.9517],
        [0.4460, 0.6858, 0.4334, 0.4663]])
 
tensor([0.1047, 0.5071, 0.0542, 0.3330, 0.8789, 0.9451, 0.8701, 0.3063, 0.7993,
        0.7721, 0.3849, 0.9517, 0.4460, 0.6858, 0.4334, 0.4663])
 
tensor([[0.4649, 0.7464],
        [0.4141, 0.8326],
        [0.0027, 0.7936],
        [0.4572, 0.6388],
        [0.8123, 0.3690],
        [0.0588, 0.7176],
        [0.6422, 0.4016],
        [0.5986, 0.0438],
        [0.8627, 0.5596]])
 
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


In [55]:
x=torch.arange(9) # Contiguous (adjacent) memory involves ordered and adjacent values stored in memory
print(x) 
y=x.view(3,3)
print(y)

print(y)
print("")

# apply transpose
y_=y.t()      # Non contiguous memory involves ordered and non adjacent values stored in memory
print(y_)
print("")
#print(y_.view(9)) # This will give an error because the memory is not contiguous
# To reshap it 
print(y_.contiguous().view(9)) # This will work because the memory is contiguous now



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [60]:
# If you do not want to specify the first shape arguments (# rows), then pass -1 and Pytorch will automaticaaly select the best shape
x=torch.rand(18)
y=x.view(-1,9)
print(y)
print("")

batch=16
x=torch.rand(batch,10,20)
y=x.view(batch,-1)
print(y.shape)

tensor([[0.2328, 0.2444, 0.0055, 0.4042, 0.1343, 0.2987, 0.7968, 0.9876, 0.2291],
        [0.1968, 0.5056, 0.1688, 0.6687, 0.9624, 0.8983, 0.1265, 0.8305, 0.8529]])

torch.Size([16, 200])


In [58]:
# Flattiing a tensor
x=torch.rand(2,3)
y=x.view(-1)
print(y)

tensor([0.9965, 0.0650, 0.0797, 0.5257, 0.3935, 0.0216])


In [61]:
# permut is used to change the order of the dimensions such as transpose operation in matrix
batch=64
samples=10
features=25
x=torch.rand(batch,features,samples)
y=x.permute(0,2,1) # 0 is the batch index, 2 is the samples, and 1 is the features
print(y.shape)

torch.Size([64, 10, 25])


In [66]:
#  Add dimension to a tensor 

'''
x = [1, 2, 3]
{x = [1, 2, 3] >>>> >>> x=x.unsqueeze(0) >>>> >>>> x = [[1, 2, 3]]}
{x = [1, 2, 3] >>>> >>> x=x.unsqueeze(1) >>>> >>>> x = x = [[1],[2],[3]]}
'''



x=torch.arange(15)
print(x.shape)
print("")

x=x.unsqueeze(0) # add a dimension at the beginning  
print(x.shape)
print("")

# Add anotehr dimension at the middle
x=x.unsqueeze(1) 
print(x.shape)
print("")


# Add anotehr dimension at the end
x=x.unsqueeze(-1) 
print(x.shape)
print("")


# Eliminate the first dimension from the beginning
x=x.squeeze(1) 
print(x.shape)
print("")



torch.Size([15])

torch.Size([1, 15])

torch.Size([1, 1, 15])

torch.Size([1, 1, 15, 1])

torch.Size([1, 15, 1])



In [57]:
# Concatinating two tensors
x1=torch.rand(4,6)
x2=torch.rand(4,6)
print(torch.cat((x1,x2),dim=0).shape) # Concatinate along the rows)    
print(torch.cat((x1,x2),dim=1).shape) # Concatinate along the columns)    

torch.Size([8, 6])
torch.Size([4, 12])


# Numpy and Pytorch conversion


In [13]:
import numpy as np

# Creating a tensor of ones
x=torch.ones(5)
print(x)
print(" ")
# Conversion to numpy
y=x.numpy()
print(y)
print(type(y))

tensor([1., 1., 1., 1., 1.])
 
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [48]:
# Note: If the tensors are located in the CPU (NOT the GPUs), then the tensor and converted np array point to the same memory address.
x=torch.ones(5)
print(x)
print(" ")

# Conversion to numpy
y=x.numpy()
print(y)
print(" ")

# Let us add 3 inplace to all matrix x. Note again: anay  method with trainling _ is used in place
x.add_(3)
print(x)
print(y)

# Thus be carfull when you make the conversion and using the inplace methods


tensor([1., 1., 1., 1., 1.])
 
[1. 1. 1. 1. 1.]
 
tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [21]:
# Numpy to Pytorch conversion
x=np.ones(5)
print(x)

# Coversion
y = torch.from_numpy(x)
y1 = torch.from_numpy(x).to(torch.float32)

print(y)
print(" ")

x+=5

print(x)
print(" ")
print(y)
print(" ")
print(y1)  # This will not be modified

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
 
[6. 6. 6. 6. 6.]
 
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)
 
tensor([1., 1., 1., 1., 1.])


In [22]:
# Check if the GPU is available or not
if torch.cuda.is_available():
    print(f'The total number of availabe GPUs are: {torch.cuda.device_count()}')

for i in range(torch.cuda.device_count()):
    device=torch.cuda.get_device_properties(i))
    print(f'\nDetails from the GPU {i}')
    print(f'Name : {device.name}')
    print(f'Compute cabability: {device.major}.{device.minor}')
    print(f'Total memory: {device.total_memory/1024**3:.2f} GB')


The total number of availabe GPUs are: 4

Details from the GPU 0
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB

Details from the GPU 1
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB

Details from the GPU 2
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB

Details from the GPU 3
Name : NVIDIA RTX A6000
Compute cabability: 8.6
Total memory: 47.54 GB


In [7]:
# Creating a tensor into a GPU
if torch.cuda.is_available():
    device=torch.device("cuda:0") # We can set the desired gpu
    x=torch.rand(5,5,device=device)
    # Alternativelly
    y=torch.rand(5,5)
    y=y.to(device)
    # Addition
    z=x+y
    print(z)

tensor([[0.4412, 0.6757, 1.5678, 0.8500, 0.7999],
        [1.0786, 0.6483, 1.5910, 1.1502, 1.4139],
        [0.8372, 0.9341, 0.3341, 0.4727, 1.2235],
        [1.5364, 0.8016, 0.6310, 1.2169, 0.9612],
        [1.3565, 0.8035, 1.1249, 1.1857, 1.4396]], device='cuda:0')


In [20]:
# Creating a tensor into a GPU or cpu 
# cpu
x=torch.tensor([[2.5,2.3],[3.5,3.3]],dtype=torch.float32,device='cpu')
print(x)

# GPU
x=torch.tensor([[2.5,2.3],[3.5,3.3]],dtype=torch.float32,device='cuda')
print(x)
print(x.dtype)
print(x.device)
print(x.size())
print(x.size(0))
print(x.shape)
print(x.shape[0])
print(x.requires_grad)

tensor([[2.5000, 2.3000],
        [3.5000, 3.3000]])
tensor([[2.5000, 2.3000],
        [3.5000, 3.3000]], device='cuda:0')
torch.float32
cuda:0
torch.Size([2, 2])
2
torch.Size([2, 2])
2
False


In [24]:
# Note: Numpy can handle only cpu tensors, thus the follwoing line of code will return an error
#z.numpy()

# Thus we can move z from the GPU to cpu to convert it into numpy
z=z.to("cpu")

znumpy=z.numpy()
print(type(znumpy))

<class 'numpy.ndarray'>


In [37]:
# Telling pytorch that the tensor need to calculate the gradient
x=torch.rand(5,6,requires_grad=True) 
print(x) # requires_grad=True will be printed and in informs teh pytorch that the tensor require gradient calculations.

tensor([[0.1184, 0.4573, 0.5545, 0.1520, 0.5867, 0.6577],
        [0.2050, 0.3934, 0.4485, 0.9007, 0.0036, 0.3371],
        [0.0056, 0.5949, 0.8334, 0.0306, 0.7424, 0.8395],
        [0.4566, 0.2756, 0.9948, 0.7113, 0.0781, 0.5844],
        [0.1381, 0.2350, 0.8446, 0.5974, 0.3487, 0.8691]], requires_grad=True)


In [27]:
x=torch.rand(5,5,requires_grad=True)
print(x)

tensor([[0.8278, 0.0268, 0.8620, 0.0368, 0.6558],
        [0.3227, 0.1824, 0.3449, 0.4699, 0.8693],
        [0.3718, 0.6464, 0.3250, 0.1720, 0.6946],
        [0.7781, 0.3550, 0.7605, 0.2204, 0.9655],
        [0.6405, 0.1738, 0.8970, 0.4033, 0.4720]], requires_grad=True)
